[package]
name = "boomlet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Boomlet domain state machine for setup, backup, and withdrawal protocol steps."
readme = "README.md"
repository.workspace = true

[dependencies]
protocol = { workspace = true }
tracing_utils = { workspace = true }
descriptor = { workspace = true }
bitcoin_utils = { workspace = true }
cryptography = { workspace = true }
bitcoin = { workspace = true }
miniscript = { workspace = true, features = ["compiler", "serde"] }
musig2 = { workspace = true, features = ["serde", "secp256k1"] }
derive_more = { workspace = true, features = ["debug", "display", "error"] }
secrecy = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
rand = { workspace = true }
strum = { workspace = true, features = ["derive"] }

[lints]
workspace = true
