use bitcoin::Network;
use poc::{setup, withdrawal};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Setting constants.
    // Path to executables.
    #[cfg(target_os = "linux")]
    const BITCOIND_EXECUTABLE_PATH: &str = "poc/bitcoin-29.0/bitcoind_linux";
    #[cfg(target_os = "macos")]
    const BITCOIND_EXECUTABLE_PATH: &str = "poc/bitcoin-29.0/bitcoind_mac";

    // Network type.
    const NETWORK: Network = Network::Regtest;

    // Miner settings.
    const INITIAL_MINER_NUM_BLOCKS_TO_MINE: u64 = 101;
    const MINER_NUM_BLOCKS_TO_MINE_FOR_DEPOSIT_TRANSACTION_TO_BE_MINED: u64 = 99;
    const MINER_TASK_SLEEPING_TIME_IN_MILLISECONDS: u64 = 100;

    // Milestone blocks that define the descriptor.
    const MILESTONE_BLOCK_0: u32 = 200;
    const MILESTONE_BLOCK_1: u32 = 500;
    const MILESTONE_BLOCK_2: u32 = 550;
    const MILESTONE_BLOCK_3: u32 = 600;
    const MILESTONE_BLOCK_4: u32 = 650;
    const MILESTONE_BLOCK_5: u32 = 700;

    // Withdrawal transaction settings.
    const DEPOSIT_AMOUNT_TO_BOOMERANG_ADDRESS_IN_INT_BTC: u64 = 21;
    const ABSOLUTE_LOCKTIME_FOR_WITHDRAWAL_TRANSACTION: u64 = 300;
    const WITHDRAWAL_TRANSACTION_AMOUNT_IN_F64_BTC: f64 = 20.999;

    // Duress check settings.
    const DURESS_CHECK_INTERVAL_IN_BLOCKS: u32 = 10;

    // Digging game duration limits.
    const MIN_TRIES_FOR_DIGGING_GAME_IN_BLOCKS: u32 = 10;
    const MAX_TRIES_FOR_DIGGING_GAME_IN_BLOCKS: u32 = 100;

    // Block tolerances for withdrawal.
    // Transaction approval.
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_INITIATOR_PEER_TO_TX_APPROVAL_BY_WT: u32 = 5; // 50 minutes
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_WT_TO_RECEIVING_WT_TX_APPROVAL_BY_NON_INITIATOR_PEERS: u32 = 576; // 4 days
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEER_TO_RECEIVING_NON_INITIATOR_PEERS_TX_APPROVAL_BY_WT: u32 = 5; // 50 minutes
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEERS_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_OTHER_NON_INITIATOR_PEERS: u32 = 288; // 2 days
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_WT_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_OTHER_NON_INITIATOR_PEERS: u32 = 864; // 6 days
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEERS_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_INITIATOR_PEER: u32 = 432; // 3 days
    const TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_INITIATOR_PEER_TO_RECEIVING_ALL_NON_INITIATOR_TX_APPROVALS_BY_INITIATOR_PEER: u32 = 1008; // 1 week

    // Transaction commitment.
    const TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_PEER_TO_RECEIVING_SAR_RESPONSE_BY_WT: u32 = 5; // 50 minutes
    const TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_PEER_TO_RECEIVING_INITIATOR_PEER_TX_COMMITMENT_BY_NON_INITIATOR_PEERS: u32 = 10; // 100 minutes
    const TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_NON_INITIATOR_PEER_TO_RECEIVING_NON_INITIATOR_PEERS_TX_COMMITMENT_BY_WT_HAVING_SAR_RESPONSE_BACK_TO_WT: u32 = 5; // 50 minutes
    const TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_AND_NON_INITIATOR_PEERS_TO_RECEIVING_TX_COMMITMENT_BY_ALL_PEERS: u32 = 20; // 200 minutes
    // Digging game.
    const TOLERANCE_IN_BLOCKS_FROM_CREATING_PING_TO_RECEIVING_ALL_PINGS_BY_WT_AND_HAVING_SAR_RESPONSE_BACK_TO_WT: u32 = 3; // 30 minutes
    const TOLERANCE_IN_BLOCKS_FROM_CREATING_PONG_BY_WT_TO_REVIEWING_THE_PONG_IN_PEERS_BOOMLET: u32 =
        3; // 30 minutes
    const TOLERANCE_IN_BLOCKS_FROM_CREATING_PING_BY_OTHER_PEERS_TO_REVIEWING_THE_PING_IN_PEER_BOOMLET: u32 = 6; // 60 minutes
    const JUMP_IN_BLOCKS_IF_LAST_SEEN_BLOCK_LAGS_BEHIND_NISO_EVENT_BLOCK_HEIGHT_IN_BOOMLET: u32 =
        10;
    // Minimum distances.
    const REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_INITIATOR_PEER_TX_APPROVAL_AND_RECEIVING_ALL_NON_INITIATOR_TX_APPROVALS_BY_INITIATOR_PEER: u32 = 0;
    const REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_PEER_TX_COMMITMENT_AND_RECEIVING_ALL_TX_COMMITMENT_BY_PEERS: u32 = 0;
    const REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_PING_AND_PONG: u32 = 1;
    // Wt sleeping time.
    const WT_SLEEPING_TIME_TO_CHECK_FOR_NEW_BLOCK_IN_MILLISECONDS: u32 = 50;
    println!(
        "\nBoomerang regime starts at block:     {}",
        MILESTONE_BLOCK_0
    );
    println!(
        "Withdrawal starts at block:           {}",
        ABSOLUTE_LOCKTIME_FOR_WITHDRAWAL_TRANSACTION
    );
    println!(
        "Boomerang regime finishes at block:   {}\n",
        MILESTONE_BLOCK_1
    );
    // Running setup.
    let boomerang_entities = setup::run(
        NETWORK,
        BITCOIND_EXECUTABLE_PATH,
        MILESTONE_BLOCK_0,
        MILESTONE_BLOCK_1,
        MILESTONE_BLOCK_2,
        MILESTONE_BLOCK_3,
        MILESTONE_BLOCK_4,
        MILESTONE_BLOCK_5,
        DURESS_CHECK_INTERVAL_IN_BLOCKS,
        MIN_TRIES_FOR_DIGGING_GAME_IN_BLOCKS,
        MAX_TRIES_FOR_DIGGING_GAME_IN_BLOCKS,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_INITIATOR_PEER_TO_TX_APPROVAL_BY_WT,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_WT_TO_RECEIVING_WT_TX_APPROVAL_BY_NON_INITIATOR_PEERS,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEER_TO_RECEIVING_NON_INITIATOR_PEERS_TX_APPROVAL_BY_WT,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEERS_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_OTHER_NON_INITIATOR_PEERS,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_INITIATOR_PEER_TO_RECEIVING_ALL_NON_INITIATOR_TX_APPROVALS_BY_INITIATOR_PEER,
        REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_INITIATOR_PEER_TX_APPROVAL_AND_RECEIVING_ALL_NON_INITIATOR_TX_APPROVALS_BY_INITIATOR_PEER,
        TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_PEER_TO_RECEIVING_SAR_RESPONSE_BY_WT,
        TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_PEER_TO_RECEIVING_INITIATOR_PEER_TX_COMMITMENT_BY_NON_INITIATOR_PEERS,
        TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_INITIATOR_AND_NON_INITIATOR_PEERS_TO_RECEIVING_TX_COMMITMENT_BY_ALL_PEERS,
        TOLERANCE_IN_BLOCKS_FROM_CREATING_PING_TO_RECEIVING_ALL_PINGS_BY_WT_AND_HAVING_SAR_RESPONSE_BACK_TO_WT,
        TOLERANCE_IN_BLOCKS_FROM_CREATING_PONG_BY_WT_TO_REVIEWING_THE_PONG_IN_PEERS_BOOMLET,
        TOLERANCE_IN_BLOCKS_FROM_CREATING_PING_BY_OTHER_PEERS_TO_REVIEWING_THE_PING_IN_PEER_BOOMLET,
        JUMP_IN_BLOCKS_IF_LAST_SEEN_BLOCK_LAGS_BEHIND_NISO_EVENT_BLOCK_HEIGHT_IN_BOOMLET,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_NON_INITIATOR_PEERS_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_INITIATOR_PEER,
        TOLERANCE_IN_BLOCKS_FROM_TX_APPROVAL_BY_WT_TO_RECEIVING_NON_INITIATOR_TX_APPROVAL_BY_OTHER_NON_INITIATOR_PEERS,
        TOLERANCE_IN_BLOCKS_FROM_TX_COMMITMENT_BY_NON_INITIATOR_PEER_TO_RECEIVING_NON_INITIATOR_PEERS_TX_COMMITMENT_BY_WT_HAVING_SAR_RESPONSE_BACK_TO_WT,
        WT_SLEEPING_TIME_TO_CHECK_FOR_NEW_BLOCK_IN_MILLISECONDS,
        REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_PEER_TX_COMMITMENT_AND_RECEIVING_ALL_TX_COMMITMENT_BY_PEERS,
        REQUIRED_MINIMUM_DISTANCE_IN_BLOCKS_BETWEEN_PING_AND_PONG,
    )?;
    // Running withdrawal.
    withdrawal::run(
        boomerang_entities,
        INITIAL_MINER_NUM_BLOCKS_TO_MINE,
        MINER_TASK_SLEEPING_TIME_IN_MILLISECONDS,
        DEPOSIT_AMOUNT_TO_BOOMERANG_ADDRESS_IN_INT_BTC,
        MINER_NUM_BLOCKS_TO_MINE_FOR_DEPOSIT_TRANSACTION_TO_BE_MINED,
        ABSOLUTE_LOCKTIME_FOR_WITHDRAWAL_TRANSACTION,
        WITHDRAWAL_TRANSACTION_AMOUNT_IN_F64_BTC,
        MIN_TRIES_FOR_DIGGING_GAME_IN_BLOCKS,
        MAX_TRIES_FOR_DIGGING_GAME_IN_BLOCKS,
    )
    .await?;

    Ok(())
}
