[package]
name = "wt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
description = "Watchtower role that coordinates Boomerang setup acknowledgements and withdrawal progress."
readme = "README.md"
repository.workspace = true

[dependencies]
protocol = { workspace = true }
tracing_utils = { workspace = true }
bitcoin_utils = { workspace = true }
cryptography = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
miniscript = { workspace = true, features = ["compiler", "serde"] }
serde = { workspace = true, features = ["derive", "serde_derive"] }
derive_more = { workspace = true, features = ["debug", "display", "error"] }
tracing = { workspace = true }
[lints.clippy]
eq_op = "allow"
